"""
Tests for UPSC daily news agent pipeline upgrades:
1. Adaptive Batch Size Adjustment in write_sections.py
2. Smart Fallback for PDF Generation (Weasyprint Resilience) in render_pdf.py
3. Email attachment file extension handling in mailer.py
"""

import os
import sys
from unittest.mock import MagicMock, patch
try:
    import weasyprint
except OSError:
    # WeasyPrint C libraries (GTK/GObject) are missing. Mock it so tests can run.
    weasyprint = MagicMock()
    sys.modules["weasyprint"] = weasyprint

import json
import pytest
from pathlib import Path
from app.agents.write_sections import write_sections
from app.agents.render_pdf import render_pdf
from app.services.mailer import MailerService


def test_adaptive_batching():
    """Test that batch sizes adaptively partition based on unit depths and sizes."""
    # Mock settings
    mock_settings = MagicMock()
    mock_settings.writer_batch_size = 10
    mock_settings.nim_api_key = "test_key"
    mock_settings.nim_base_url = "test_url"
    mock_settings.nim_model_fast = "test_model"
    mock_settings.llm_max_retries = 1
    mock_settings.llm_timeout = 10
    mock_settings.llm_delay_seconds = 0.0

    state = {
        "run_id": "test_run",
        "verified_units": [],
        "articles_normalized": [],
        "section_buffers": {},
    }

    # Generate mock units:
    # 1. 15 simple prelims booster snippets (prelims_only) under a valid section like gs3_scitech
    prelims_units = []
    prelims_buffer_items = []
    for i in range(15):
        uid = f"prelims_{i}"
        prelims_units.append({
            "unit_id": uid,
            "title": f"Prelims Fact {i}",
            "factual_summary": ["A simple fact."],
            "prelims_facts": ["Fact detailed"],
            "prelims_metadata": {"nodal_ministry_or_agency": "N/A"},
            "content_depth": "prelims_only"
        })
        prelims_buffer_items.append({
            "unit_id": uid,
            "content_depth": "prelims_only",
            "priority": 5,
        })

    # 2. 3 very long editorials (>6,000 characters serialized)
    editorial_units = []
    editorial_buffer_items = []
    for i in range(3):
        uid = f"edit_{i}"
        editorial_units.append({
            "unit_id": uid,
            "title": f"Editorial analysis of policy reform {i}",
            "factual_summary": ["A very long summary line."] * 200,  # Make it long (>6,000 chars)
            "why_it_matters": ["Significance details."] * 200,
            "content_depth": "full"
        })
        editorial_buffer_items.append({
            "unit_id": uid,
            "content_depth": "full",
            "priority": 5,
        })

    # Put in state
    state["verified_units"] = prelims_units + editorial_units
    state["section_buffers"] = {
        "gs3_scitech": prelims_buffer_items,
        "editorial": editorial_buffer_items,
    }

    with patch("config.settings.get_settings", return_value=mock_settings), \
         patch("app.services.llm_client.LLMClient") as MockLLM:
        
        mock_llm_instance = MockLLM.return_value
        mock_llm_instance.write_section.return_value = "<div class='brief-card'><h3>Article</h3></div>"
        mock_llm_instance.total_calls = 1
        mock_llm_instance.total_tokens = 100

        result = write_sections(state)

        # Let's inspect the batches generated by checking the calls to write_section
        # Collect arguments sent to write_section
        write_section_calls = mock_llm_instance.write_section.call_args_list
        
        # There should be 4 batches (2 for prelims booster in gs3_scitech, 2 for editorial)
        assert len(write_section_calls) == 4
        
        # Verify the contents of the batches:
        # First prelims booster batch should contain 10 units
        prelims_calls = [c for c in write_section_calls if "GS3: Science & Technology" in str(c)]
        assert len(prelims_calls) == 2
        
        # Parse the JSON string sent to verified_units_json
        prelims_batch_1 = json.loads(prelims_calls[0].kwargs["verified_units_json"])
        prelims_batch_2 = json.loads(prelims_calls[1].kwargs["verified_units_json"])
        assert len(prelims_batch_1) == 10
        assert len(prelims_batch_2) == 5

        # Editorial batches should split (2, then 1)
        editorial_calls = [c for c in write_section_calls if "Editorial & Explained Analysis" in str(c)]
        assert len(editorial_calls) == 2
        editorial_batch_1 = json.loads(editorial_calls[0].kwargs["verified_units_json"])
        editorial_batch_2 = json.loads(editorial_calls[1].kwargs["verified_units_json"])
        assert len(editorial_batch_1) == 2
        assert len(editorial_batch_2) == 1


def test_weasyprint_resilience_fallback(tmp_path):
    """Test that render_pdf correctly strips CSS on WeasyPrint failure and saves HTML on double failure."""
    mock_settings = MagicMock()
    mock_settings.output_path = tmp_path / "output"
    mock_settings.output_path.mkdir()
    mock_settings.run_dir.return_value = tmp_path / "run"
    mock_settings.run_dir.return_value.mkdir(parents=True)

    html_file = tmp_path / "compiled_digest.html"
    html_content = """
    <html>
    <head>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter');
            body { font-family: 'Inter'; background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); }
            .brief-card { display: flex; }
        </style>
        <link rel="stylesheet" href="https://example.com/missing.css">
    </head>
    <body>
        <div class="brief-card">
            <h3>Article Title</h3>
        </div>
    </body>
    </html>
    """
    html_file.write_text(html_content, encoding="utf-8")

    state = {
        "compiled_html_path": str(html_file),
        "run_id": "test_run_123",
        "run_date": "2026-06-10",
    }

    # Simulate WeasyPrint failing on initial render, succeeding on stripped retry
    with patch("config.settings.get_settings", return_value=mock_settings), \
         patch("weasyprint.HTML") as MockHTML, \
         patch("time.time", return_value=1.0):
        
        mock_doc = MagicMock()
        mock_doc.pages = [1, 2]
        
        # First call to HTML(filename=...) works, but render() throws an exception (e.g. invalid stylesheet link)
        mock_html_inst1 = MagicMock()
        mock_html_inst1.render.side_effect = Exception("Weasyprint syntax/network error")
        
        # Second call to HTML(filename=...) during retry works
        mock_html_inst2 = MagicMock()
        mock_html_inst2.render.return_value = mock_doc
        
        MockHTML.side_effect = [mock_html_inst1, mock_html_inst2]

        result = render_pdf(state)

        assert result["current_phase"] == "rendered"
        assert result["metrics"]["actual_pages"] == 2
        assert "compiled_pdf_path" in result
        
        # Verify fallback HTML file exists and does NOT contain @import or link styles
        fallback_file = html_file.parent / "compiled_digest_fallback.html"
        assert fallback_file.exists()
        cleaned_html = fallback_file.read_text(encoding="utf-8")
        assert "@import" not in cleaned_html
        assert "missing.css" not in cleaned_html
        assert "Georgia, serif" in cleaned_html  # basic fallback CSS injected


def test_weasyprint_double_fallback_html(tmp_path):
    """Test that render_pdf saves HTML and auto-opens on double failure."""
    mock_settings = MagicMock()
    mock_settings.output_path = tmp_path / "output"
    mock_settings.output_path.mkdir()
    mock_settings.run_dir.return_value = tmp_path / "run"
    mock_settings.run_dir.return_value.mkdir(parents=True)

    html_file = tmp_path / "compiled_digest.html"
    html_file.write_text("<html><body>Test</body></html>", encoding="utf-8")

    state = {
        "compiled_html_path": str(html_file),
        "run_id": "test_run_123",
        "run_date": "2026-06-10",
    }

    # Both initial render and retry fail
    with patch("config.settings.get_settings", return_value=mock_settings), \
         patch("weasyprint.HTML") as MockHTML, \
         patch("webbrowser.open") as mock_webbrowser_open:
        
        mock_html_inst = MagicMock()
        mock_html_inst.render.side_effect = Exception("Fatal crash")
        MockHTML.return_value = mock_doc = mock_html_inst

        result = render_pdf(state)

        # Output should fall back to HTML
        assert result["current_phase"] == "rendered_html_only"
        assert result["compiled_pdf_path"].endswith(".html")
        assert Path(result["compiled_pdf_path"]).exists()
        
        # Verify print warning script is injected
        html_res = Path(result["compiled_pdf_path"]).read_text(encoding="utf-8")
        assert "window.print()" in html_res
        
        # Verify webbrowser.open was called
        mock_webbrowser_open.assert_called_once()


def test_mailer_dynamic_attachment(tmp_path):
    """Test that MailerService attaches HTML files with the correct MIME type."""
    mailer = MailerService(
        smtp_host="localhost",
        smtp_port=1025,
        smtp_user="test",
        smtp_pass="test",
        email_from="test@example.com",
    )

    recipients = ["recipient@example.com"]
    date_str = "2026-06-10"

    html_file = tmp_path / "digest.html"
    html_file.write_text("<html><body>Digest</body></html>", encoding="utf-8")

    with patch("smtplib.SMTP") as MockSMTP:
        mock_smtp_instance = MockSMTP.return_value
        
        result = mailer.send_digest(
            recipients=recipients,
            pdf_path=html_file,
            date_str=date_str,
            article_count=5,
            page_count=0,
            themes=["Theme 1"],
        )

        assert result["delivered"] is True
        
        # Check SMTP call and message content on the context manager enter return value
        mock_smtp_instance.__enter__.return_value.sendmail.assert_called_once()
        sent_msg_str = mock_smtp_instance.__enter__.return_value.sendmail.call_args[0][2]
        
        # Verify attachment headers in MIME raw string
        assert 'Content-Type: application/html' in sent_msg_str or 'Content-Type: application/octet-stream' in sent_msg_str
        assert f'filename="UPSC_Digest_{date_str}.html"' in sent_msg_str
